name: "Deploy"

on:
    push:
        branches:
            - master
    workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    helloworld:
        runs-on: ubuntu-latest
        steps:
            - name: "Decir hola mundo"
              run: echo "Hello World"
            - name: "Traernos el codigo"
              uses: actions/checkout@v4
            - name: "ver archivos"
              run: ls
            - uses: withastro/action@v3
              with:
                package-manager: pnpm@7
    deploy:
      needs: helloworld
      runs-on: ubuntu-latest
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
