name: "Mi primer workflow"

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    helloworld:
        runs-on: ubuntu-latest
        steps:
            - name: "Decir hola mundo"
              run: echo "Hello World"
            - name: "Traernos el codigo"
              uses: actions/checkout@v4
            - name: "ver archivos"
              run: ls