name: "Mi primer workflow"

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    helloworld:
        runs-on: ubuntu-latest
        steps:
            - name: "Decir hola mundo"
              run: echo "Hello World"
            - name: "Traernos el codigo"
              uses: actions/checkout@v4
            - name: "ver archivos"
              run: ls
            - name: "Install node js"
              uses: actions/setup-node@v4
            - name: "Instalar dependencias"
              run: npm install
            - name: "Linter"
              run: npm run lint
            - name: "Correr pruebas"
              run: echo "tests"
            - name: "Build"
              run: npm run build
            - name: "Deploy"
              run: ls
